{
    'version': '3.7',
    'services':
        {
            'mongo':
                {
                    'image': 'mongo:4.2.15',
                    'restart': 'always',
                    'ports': ['27017:27017'],
                    'environment':
                        {
                            'MONGO_INITDB_DATABASE': 'satandb',
                            'MONGO_INITDB_ROOT_USERNAME': 'root',
                            'MONGO_INITDB_ROOT_PASSWORD': 'satans-passwd',
                        },
                    'volumes':
                        [
                            'mongo-data:/data/db',
                            ./scripts/docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro,
                        ],
                },
            'satanbot':
                {
                    'depends_on': ['mongo'],
                    'restart': 'always',
                    'build': { 'context': '.', 'dockerfile': 'Dockerfile' },
                },
        },
    'volumes': { 'mongo-data': null },
}
