services:
    mongo:
        image: mongo
        restart: always
        ports:
            - '27017:27017'
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: satanDB
        volumes:
            - 'mongo-data:/data/db'
    satanbot:
        depends_on:
            - mongo
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
volumes:
    mongo-data:
