export const TYPES = {
    Bot: Symbol('Bot'),
    Client: Symbol('Client'),
    MongoAccess: Symbol('MongoAccess'),
    Token: Symbol('Token'),
    MongoConnectionString: Symbol('MongoConnectionString'),
    MessageService: Symbol('MessageService'),
    MessageLogService: Symbol('MessageLogService'),
    NewMessageLogRepository: Symbol('NewMessageLogRepository'),
    EditedMessageLogRepository: Symbol('EditedMessageLogRepository'),
    EditedMessageLogService: Symbol('EditedMessageLogService'),
    DeletedMessageLogRepository: Symbol('DeletedMessageLogRepository'),
    DeletedMessageLogService: Symbol('DeletedMessageLogService'),
    VoiceTimeRepository: Symbol('VoiceTimeRepository'),
    VoiceStatusRepository: Symbol('VoiceStatusRepository'),
    VoiceStatusService: Symbol('VoiceStatusService'),
    VoiceTimeService: Symbol('VoiceTimeService'),
    ChannelService: Symbol('ChannelService'),
    MemberStatusRepository: Symbol('MemberStatusRepository'),
    MemberService: Symbol('MemberService'),
    TierListService: Symbol('TierListService'),
};
